#define SQL_CreateRuleTable "CREATE TABLE RULE ( ID nteger PRIMARY KEY autoincrement, TASKNAME TEXT, PROGRAMTITLE TEXT, PROGRAMDIRECTORY TEXT, RUNPATH TEXT, \
RUNNINGRULE INT, STARTTIMESEC INT,STARTTIMEUSEC INT, ENDTIMESEC INT ENDTIMEUSEC INT, PERPERIODTIMESEC INT, PERPERIODTIMEUSEC INT, TIMES INT, TOTALTIMESEC INT\
, TOTALTIMEUSEC INT LIMITRULE INT )"

#define SQL_DeleteRule ""